- src/app/card/card.component.html
- src/app/card/card.component.spec.ts
- src/app/card/card.component.ts
- src/app/tab1/tab1.module.ts
- src/app/tab1/tab1.page.html
create a card component for testing.
> update Ionic code 

- Cyclops/src/app/progress-indicators/progress-indicators.component.html
- Cyclops/src/app/progress-indicators/progress-indicators.component.scss
- Cyclops/src/app/progress-indicators/progress-indicators.component.spec.ts
- Cyclops/src/app/progress-indicators/progress-indicators.component.ts
- Cyclops/src/app/tab1/tab1.module.ts
- Cyclops/src/app/tab1/tab1.page.html
demonstrate Progress Indicators on Tab1
> Explore Progress Indicators

- tech_tranning_completion_record/Tutorial Question/Week8/Sumeet_week8.html
> Finished questions for Sumeet_week8.html

- Cyclops/src/app/popover/popover.component.html
- Cyclops/src/app/popover/popover.component.scss
- Cyclops/src/app/popover/popover.component.spec.ts
- Cyclops/src/app/popover/popover.component.ts
- Cyclops/src/app/tab3/tab3.module.ts
- Cyclops/src/app/tab3/tab3.page.html
- Cyclops/src/app/tab3/tab3.page.ts
> Popover Component added to tab3 under the slide components

- Cyclops/src/app/page-space-su/form/solution.page.form.spec.ts
- Cyclops/src/app/page-space-su/form/solution.page.form.ts
- Cyclops/src/app/page-space-su/page-space-su.module.ts
- Cyclops/src/app/page-space-su/page-space-su.page.html
- Cyclops/src/app/page-space-su/page-space-su.page.scss
- Cyclops/src/app/page-space-su/page-space-su.page.spec.ts
- Cyclops/src/app/page-space-su/page-space-su.page.ts
- Cyclops/src/app/page-space-su/progress-indicators/progress-indicators.component.html
- Cyclops/src/app/page-space-su/progress-indicators/progress-indicators.component.ts
- Cyclops/src/app/page-space-su/score-modal/score-modal.component.html
- Cyclops/src/app/page-space-su/score-modal/score-modal.component.scss
- Cyclops/src/app/page-space-su/score-modal/score-modal.component.spec.ts
- Cyclops/src/app/page-space-su/score-modal/score-modal.component.ts
User's can now input a score on eco tracker page
> Page4 score implementation

- Cyclops/src/app/page-space-er/page-space-er.page.html
> Page1 styling eric

- Cyclops/src/app/page-space-su/page-space-su.page.html
- Cyclops/src/app/page-space-su/page-space-su.page.ts
- Cyclops/src/app/page-space-su/score-modal/score-modal.component.html
- Cyclops/src/app/page-space-su/score-modal/score-modal.component.scss
- Cyclops/src/app/page-space-su/score-modal/score-modal.component.ts
> Multiple soution sumeet

- Cyclops/package-lock.json
- Cyclops/package.json
- Cyclops/src/app/app-routing.module.ts
- Cyclops/src/app/editing-tool-test-page/editing-tool-test-page-routing.module.ts
- Cyclops/src/app/editing-tool-test-page/editing-tool-test-page.module.ts
- Cyclops/src/app/editing-tool-test-page/editing-tool-test-page.page.html
- Cyclops/src/app/editing-tool-test-page/editing-tool-test-page.page.spec.ts
- Cyclops/src/app/editing-tool-test-page/editing-tool-test-page.page.ts
Using CKEditor Plugin as the Editing Tool
Installed the tool for Angular in this project
Configured the project to use modules
> Editing tool Component Installation

- Cyclops/src/app/app-routing.module.ts
- Cyclops/src/app/editing-tool-test-page/editing-tool-test-page.page.html
- Cyclops/src/app/editing-tool-test-page/editing-tool-test-page.page.scss
- Cyclops/src/app/editing-tool-test-page/editing-tool-test-page.page.ts
- Cyclops/src/app/page-space-la/article-main/article-main.component.html
- Cyclops/src/app/page-space-la/article-main/article-main.component.ts
- Cyclops/src/app/tabs/tabs-routing.module.ts
> Editing tool demo

- Cyclops/src/app/page-space-la/article-main/article-main.component.html
- Cyclops/src/app/page-space-la/article-main/article-main.component.ts
- Cyclops/src/app/page-space-la/page-space-la.page.html
- Cyclops/src/app/page-space-la/page-space-la.page.ts
- Cyclops/src/app/page-space-su/page-space-su.page.html
> Megan gridtest

- Cyclops/backend/delete.php
- Cyclops/src/app/service.service.ts
> Database demo2 eric

- Cyclops/src/app/editing-tool-test-page/editing-tool-test-page.page.ts
> Bug fix article edit display

- Cyclops/backend/updateName.php
- Cyclops/src/app/service.service.ts
> Database demo3 eric

- Cyclops/src/app/add-data/add-data.page.html
- Cyclops/src/app/add-data/add-data.page.ts
- Cyclops/src/app/app-routing.module.ts
- Cyclops/src/app/firebase.service.ts
- Cyclops/src/app/page-space-er/page-space-er.page.html
- Cyclops/src/app/page-space-er/page-space-er.page.ts
- Cyclops/src/app/page-space-me/page-space-me.page.html
- Cyclops/src/app/page-space-me/page-space-me.page.ts
> Firestore eric

- Cyclops/src/app/page-space-er/page-space-er.page.ts
- Cyclops/src/app/page-space-la/article-main/article-main.component.html
- Cyclops/src/app/page-space-la/article-main/article-main.component.ts
- Cyclops/src/app/page-space-la/page-space-la.page.html
- Cyclops/src/app/page-space-la/page-space-la.page.ts
- Cyclops/src/app/page-space-me/page-space-me.page.html
- Cyclops/src/app/page-space-me/page-space-me.page.ts
> Articlepage loading

- Cyclops/src/app/app.component.html
- Cyclops/src/app/app.component.scss
- Cyclops/src/app/page-space-er/page-space-er.page.html
- Cyclops/src/app/page-space-er/page-space-er.page.scss
- Cyclops/src/app/page-space-er/page-space-er.page.ts
- Cyclops/src/app/page-space-er/services/screensize.service.spec.ts
- Cyclops/src/app/page-space-er/services/screensize.service.ts
> Split pane sumeet

- Cyclops/src/app/app.component.scss
Increased width on side menu, for better overall look. Eco Tracker label now shows in one row.
Updated scss to reintroduce border, rather than a no border look
> Updated Styling on Side menu

- Cyclops/package-lock.json
- Cyclops/src/app/app-routing.module.ts
- Cyclops/src/app/editing-tool-test-page/editing-tool-test-page.page.html
- Cyclops/src/app/editing-tool-test-page/editing-tool-test-page.page.ts
- Cyclops/src/app/page-space-la/article-main/article-main.component.html
> Data interaction database

- Cyclops/src/app/add-data/add-data.page.html
- Cyclops/src/app/add-data/add-data.page.ts
- Cyclops/src/app/firebase.service.ts
> Authentication eric

- Cyclops/src/app/editing-tool-test-page/editing-tool-test-page.page.html
- Cyclops/src/app/editing-tool-test-page/editing-tool-test-page.page.scss
- Cyclops/src/app/editing-tool-test-page/editing-tool-test-page.page.ts
> Text edit page confirmation

- Cyclops/src/app/page-space-la/page-space-la.page.html
- Cyclops/src/app/page-space-la/page-space-la.page.ts
> Segment button new

- Cyclops/src/app/page-space-su/page-space-su.page.html
- Cyclops/src/app/page-space-su/star-modal/star-modal.component.html
- Cyclops/src/app/page-space-su/star-modal/star-modal.component.ts
> Implemented placeholder values for eco tracker input

- Cyclops/src/app/app.module.ts
- Cyclops/src/app/auth/auth.service.ts
- Cyclops/src/app/registration/registration.module.ts
- Cyclops/src/app/registration/registration.page.html
- Cyclops/src/app/registration/registration.page.scss
- Cyclops/src/app/registration/registration.page.ts
- Cyclops/src/app/sharedData/user.ts
> Improvement on auth eric

- Cyclops/src/app/login/login.module.ts
- Cyclops/src/app/login/login.page.html
- Cyclops/src/app/login/login.page.scss
- Cyclops/src/app/login/login.page.ts
- Cyclops/src/app/registration/registration.page.html
> add input checking and improvement on UI of login page

- Cyclops/src/app/auth/auth.service.ts
- Cyclops/src/app/login/login.page.html
- Cyclops/src/app/registration/registration.page.html
> Completed sign-in with google

- Cyclops/src/app/page-space-su/page-space-su.page.ts
- Cyclops/src/app/page-space-su/score-modal/enum.ts
- Cyclops/src/app/page-space-su/score-modal/score-modal.component.html
- Cyclops/src/app/page-space-su/score-modal/score-modal.component.scss
- Cyclops/src/app/page-space-su/score-modal/score-modal.component.ts
> 5 Leaf scoring system

- Cyclops/src/app/page-space-la/page-space-la.page.html
- Cyclops/src/app/page-space-la/page-space-la.page.scss
- Cyclops/src/app/page-space-la/page-space-la.page.ts
> Search bar component update

- Cyclops/src/app/page-space-su/page-space-su.page.ts
- Cyclops/src/app/page-space-su/score-modal/SectionSolution.ts
- Cyclops/src/app/page-space-su/score-modal/score-modal.component.html
- Cyclops/src/app/page-space-su/score-modal/score-modal.component.scss
- Cyclops/src/app/page-space-su/score-modal/score-modal.component.ts
- Cyclops/src/app/sharedData/SectionSolution.ts
> Eco tracker input formatting sumeet

- Cyclops/src/app/add-data/add-data.page.html
- Cyclops/src/app/add-data/add-data.page.ts
- Cyclops/src/app/firebase.service.ts
> Megan article tracking

- Cyclops/src/app/page-space-su/page-space-su.page.html
- Cyclops/src/app/page-space-su/page-space-su.page.ts
- Cyclops/src/app/page-space-su/score-modal/score-modal.component.html
- Cyclops/src/app/page-space-su/score-modal/score-modal.component.scss
- Cyclops/src/app/page-space-su/score-modal/score-modal.component.ts
> Eco tracker form validations- Without rating validations(In Progress)

- Cyclops/src/app/add-data/add-data.page.ts
- Cyclops/src/app/authentication/auth/auth.service.ts
- Cyclops/src/app/page-space-me/page-space-me.page.ts
> Async data bug fix

- Cyclops/src/app/app-routing.module.ts
- Cyclops/src/app/authentication/auth/auth.service.ts
- Cyclops/src/app/authentication/reset-password/reset-password.page.html
- Cyclops/src/app/guard/auth.guard.spec.ts
- Cyclops/src/app/guard/auth.guard.ts
- Cyclops/src/app/guard/login.guard.spec.ts
- Cyclops/src/app/guard/login.guard.ts
> Router guards eric

- Cyclops/src/app/page-space-su/page-space-su.page.ts
- Cyclops/src/app/page-space-su/score-modal/SectionSolution.ts
- Cyclops/src/app/page-space-su/score-modal/SectionSolutionTags.ts
- Cyclops/src/app/page-space-su/score-modal/score-modal.component.ts
> Data formatting eco

- Cyclops/src/app/page-space-la/page-space-la.page.ts
> fix progress bar display while not logged in bug

- Cyclops/src/app/page-space-su/page-space-su.page.html
- Cyclops/src/app/page-space-su/page-space-su.page.ts
- Cyclops/src/app/page-space-su/score-modal/score-modal.component.html
- Cyclops/src/app/page-space-su/score-modal/score-modal.component.scss
- Cyclops/src/app/page-space-su/score-modal/score-modal.component.ts
> Ion range slider sumeet

- Cyclops/src/app/app-routing.module.ts
- Cyclops/src/app/firebaseService/firebase.service.ts
- Cyclops/src/app/page-space-er/page-space-er-routing.module.ts
- Cyclops/src/app/page-space-er/page-space-er.page.html
- Cyclops/src/app/page-space-er/page-space-er.page.scss
- Cyclops/src/app/page-space-er/page-space-er.page.ts
- Cyclops/src/app/userProfile/edit-survey-details/edit-survey-details-routing.module.ts
- Cyclops/src/app/userProfile/edit-survey-details/edit-survey-details.module.ts
- Cyclops/src/app/userProfile/edit-survey-details/edit-survey-details.page.html
- Cyclops/src/app/userProfile/edit-survey-details/edit-survey-details.page.scss
- Cyclops/src/app/userProfile/edit-survey-details/edit-survey-details.page.spec.ts
- Cyclops/src/app/userProfile/edit-survey-details/edit-survey-details.page.ts
- Cyclops/src/app/userProfile/edit-survey/edit-survey-routing.module.ts
- Cyclops/src/app/userProfile/edit-survey/edit-survey.module.ts
- Cyclops/src/app/userProfile/edit-survey/edit-survey.page.html
- Cyclops/src/app/userProfile/edit-survey/edit-survey.page.scss
- Cyclops/src/app/userProfile/edit-survey/edit-survey.page.spec.ts
- Cyclops/src/app/userProfile/edit-survey/edit-survey.page.ts
- Cyclops/src/app/userProfile/user-profile/user-profile.page.html
- Cyclops/src/app/userProfile/user-profile/user-profile.page.ts
- Cyclops/src/theme/variables.scss
> Survey eric

- Cyclops/src/app/page-space-la/page-space-la.page.html
- Cyclops/src/app/page-space-la/page-space-la.page.scss
> Progress bar styling

- Cyclops/src/app/page-space-er/page-space-er-routing.module.ts
- Cyclops/src/app/page-space-er/page-space-er.page.html
- Cyclops/src/app/page-space-er/welcome-message/welcome-message-routing.module.ts
- Cyclops/src/app/page-space-er/welcome-message/welcome-message.module.ts
- Cyclops/src/app/page-space-er/welcome-message/welcome-message.page.html
- Cyclops/src/app/page-space-er/welcome-message/welcome-message.page.scss
- Cyclops/src/app/page-space-er/welcome-message/welcome-message.page.spec.ts
- Cyclops/src/app/page-space-er/welcome-message/welcome-message.page.ts
> Edir main page eric

- Cyclops/src/app/editing-tool-test-page/editing-tool-test-page.page.ts
- Cyclops/src/app/page-space-la/article-edit-page/article-edit-page-routing.module.ts
- Cyclops/src/app/page-space-la/article-edit-page/article-edit-page.module.ts
- Cyclops/src/app/page-space-la/article-edit-page/article-edit-page.page.html
- Cyclops/src/app/page-space-la/article-edit-page/article-edit-page.page.spec.ts
- Cyclops/src/app/page-space-la/article-edit-page/article-edit-page.page.ts
- Cyclops/src/app/page-space-la/article-edit/article-edit.component.html
- Cyclops/src/app/page-space-la/article-edit/article-edit.component.spec.ts
- Cyclops/src/app/page-space-la/article-edit/article-edit.component.ts
- Cyclops/src/app/page-space-la/article-main/article-main.component.html
- Cyclops/src/app/page-space-la/article-main/article-main.component.ts
- Cyclops/src/app/page-space-la/page-space-la-routing.module.ts
- Cyclops/src/app/page-space-la/page-space-la.page.html
- Cyclops/src/app/page-space-la/page-space-la.page.ts
> Page edit update

- Cyclops/src/app/app.component.html
> highlight the "profile" button when it is on focus

- Cyclops/src/app/editing-tool-test-page/editing-tool-test-page.page.ts
> Edit tool bug fix

- Cyclops/src/app/page-space-la/page-space-la.page.html
> Article main pwa

- Cyclops/src/app/page-space-su/score-modal/StarSolutionTags.ts
- Cyclops/src/app/page-space-su/score-modal/StarSolutions.ts
- Cyclops/src/app/page-space-su/score-modal/score-modal.component.html
- Cyclops/src/app/page-space-su/score-modal/score-modal.component.scss
- Cyclops/src/app/page-space-su/score-modal/score-modal.component.ts
> Article section scoring sumeet

- Cyclops/src/app/page-space-su/score-modal/score-modal.component.html
- Cyclops/src/app/page-space-su/score-modal/score-modal.component.scss
> Form styling eco sumeet

- Cyclops/src/app/add-data/add-data.page.html
- Cyclops/src/app/add-data/add-data.page.ts
- Cyclops/src/app/authentication/auth/auth.service.ts
- Cyclops/src/app/firebaseService/firebase.service.ts
- Cyclops/src/app/page-space-su/page-space-su.page.html
- Cyclops/src/app/page-space-su/page-space-su.page.ts
> Eco tracker database

- Cyclops/src/app/page-space-su/page-space-su.page.html
- Cyclops/src/app/page-space-su/score-modal/MainFormTags.ts
- Cyclops/src/app/page-space-su/score-modal/SectionAssign.ts
- Cyclops/src/app/page-space-su/score-modal/score-modal.component.html
- Cyclops/src/app/page-space-su/score-modal/score-modal.component.ts
> Reformatting eco sumeet

- Cyclops/src/app/page-space-su/page-space-su.page.html
- Cyclops/src/app/page-space-su/page-space-su.page.ts
> Eco tracker attend type

- Cyclops/src/app/page-space-su/page-space-su.page.html
- Cyclops/src/app/page-space-su/page-space-su.page.ts
> Eco tracker score

- Cyclops/src/app/page-space-su/page-space-su.page.html
- Cyclops/src/app/page-space-su/page-space-su.page.ts
> Improvement on eco eric

- Cyclops/src/app/page-space-su/page-space-su.page.html
> apply ion-accordion-group for the filter

- Cyclops/src/app/page-space-su/page-space-su.page.html
- Cyclops/src/app/page-space-su/page-space-su.page.scss
> Responsive Design for Eco-Tracker Filter

- Cyclops/src/app/page-space-su/page-space-su.page.html
- Cyclops/src/app/page-space-su/page-space-su.page.ts
> Eco tracker score upload

- Cyclops/src/app/page-space-er/page-space-er.page.html
- Cyclops/src/app/page-space-la/page-space-la.page.html
- Cyclops/src/app/page-space-me/page-space-me.page.html
- Cyclops/src/app/page-space-su/page-space-su.page.html
- Cyclops/src/app/page-space-su/page-space-su.page.scss
> Eco tracker rwd

- Cyclops/src/app/firebaseService/firebase.service.ts
- Cyclops/src/app/page-space-su/eco-edit/eco-edit-routing.module.ts
- Cyclops/src/app/page-space-su/eco-edit/eco-edit.module.ts
- Cyclops/src/app/page-space-su/eco-edit/eco-edit.page.html
- Cyclops/src/app/page-space-su/eco-edit/eco-edit.page.spec.ts
- Cyclops/src/app/page-space-su/eco-edit/eco-edit.page.ts
- Cyclops/src/app/page-space-su/page-space-su-routing.module.ts
- Cyclops/src/app/page-space-su/page-space-su.page.html
- Cyclops/src/app/page-space-su/page-space-su.page.scss
- Cyclops/src/app/page-space-su/page-space-su.page.ts
> Eco tracker edit feature

- Cyclops/src/app/page-space-la/article-edit-page/article-edit-page.page.ts
- Cyclops/src/app/page-space-la/article-main/article-main.component.ts
> Article bug fix

- Cyclops/src/app/page-space-su/page-space-su.page.ts
> Max Score Calculation Implemented

- Cyclops/src/app/page-space-la/article-search-page/article-search-page-routing.module.ts
- Cyclops/src/app/page-space-la/article-search-page/article-search-page.module.ts
- Cyclops/src/app/page-space-la/article-search-page/article-search-page.page.html
- Cyclops/src/app/page-space-la/article-search-page/article-search-page.page.spec.ts
- Cyclops/src/app/page-space-la/article-search-page/article-search-page.page.ts
- Cyclops/src/app/page-space-la/page-space-la-routing.module.ts
- Cyclops/src/app/page-space-la/page-space-la.page.html
- Cyclops/src/app/page-space-la/page-space-la.page.ts
> search modal works

- Cyclops/src/app/page-space-su/page-space-su.page.html
- Cyclops/src/app/page-space-su/page-space-su.page.scss
- Cyclops/src/app/page-space-su/page-space-su.page.ts
- Cyclops/src/global.scss
> Fix issue- when the description of the solution exceeds the card

- Cyclops/src/app/page-space-su/page-space-su.page.html
- Cyclops/src/app/page-space-su/page-space-su.page.scss
- Cyclops/src/app/page-space-su/page-space-su.page.ts
> Eco tracker section edit

- Cyclops/src/app/app.component.html
- Cyclops/src/app/page-space-er/page-space-er.page.html
> Megan login

- Cyclops/src/app/app-routing.module.ts
- Cyclops/src/app/app.component.ts
- Cyclops/src/app/page-space-er/page-space-er.page.html
- Cyclops/src/app/page-space-la/article-main/article-main.component.html
- Cyclops/src/app/page-space-la/article-search-page/article-search-page.page.html
- Cyclops/src/app/page-space-la/page-space-la.page.html
- Cyclops/src/app/tabs/tabs-routing.module.ts
- Cyclops/src/app/tabs/tabs.page.html
> Update routing sumeet

- Cyclops/src/app/page-space-er/page-space-er.page.html
- Cyclops/src/app/page-space-er/page-space-er.page.scss
- Cyclops/src/index.html
resolve #385 
This resolves the issue in an unintended way. I updated the <base> component in the header instead of the <ckeditor> in the article edit component
> Article link update

- Cyclops/src/app/authentication/auth/auth.service.ts
- Cyclops/src/app/authentication/reset-password/reset-password.page.html
- Cyclops/src/app/authentication/verify-email/verify-email.page.html
- Cyclops/src/app/userProfile/user-profile/user-profile.page.html
> Router fixes sumeet

- Cyclops/src/app/page-space-su/eco-edit/eco-edit.page.html
- Cyclops/src/app/page-space-su/eco-edit/eco-edit.page.ts
- Cyclops/src/app/page-space-su/page-space-su.page.ts
> Eco Solution Section Edit Bug Fix

- Cyclops/src/app/page-space-er/page-space-er.page.ts
- Cyclops/src/app/page-space-la/article-main/article-main.component.html
- Cyclops/src/app/page-space-la/article-main/article-main.component.scss
- Cyclops/src/app/page-space-la/page-space-la.page.html
- Cyclops/src/app/page-space-la/page-space-la.page.scss
> Iphone layout bug fix

- Cyclops/src/app/page-space-su/eco-add/eco-add-routing.module.ts
- Cyclops/src/app/page-space-su/eco-add/eco-add.module.ts
- Cyclops/src/app/page-space-su/eco-add/eco-add.page.html
- Cyclops/src/app/page-space-su/eco-add/eco-add.page.spec.ts
- Cyclops/src/app/page-space-su/eco-add/eco-add.page.ts
- Cyclops/src/app/page-space-su/page-space-su-routing.module.ts
- Cyclops/src/app/page-space-su/page-space-su.page.html
- Cyclops/src/app/page-space-su/page-space-su.page.ts
> Eco tracker solution addition

- Cyclops/src/app/editing-tool-test-page/editing-tool-test-page.page.html
- Cyclops/src/app/editing-tool-test-page/editing-tool-test-page.page.ts
- Cyclops/src/app/editing-tool-test-page/search-add-eco-solutions/search-add-eco-solutions.page.ts
- Cyclops/src/app/page-space-me/page-space-me.page.html
- Cyclops/src/app/page-space-me/page-space-me.page.ts
> Megan eco segment

- Cyclops/src/app/add-data/add-data.page.ts
- Cyclops/src/app/page-space-la/article-main/article-main.component.ts
> Megan read articles calculations
